# RedStarAC configuration
#
#
####################################################################################
#                                                                                  #
################################# Settings #########################################
#                                                                                  #
####################################################################################
settings:
  # Принудительно проверять игроков не смотря на Bypass
  force_check: true
####################################################################################
#                                                                                  #
################################# Messages #########################################
#                                                                                  #
####################################################################################
messages:
  unknown: "§c[RedStarAC] §fНеизвестная команда!"
  no_perms: "§c[RedStarAC] §fУ вас нету доступа к этой команде!"
  kick: "§c[RedStarAC] §f%cheater% успешно кикнут!"
  kick_you: "§cRedStarAC§f \nВы были кикнуты античитом!"
  bypass_kick: "§c[RedStarAC] §fВы не можете кикнуть этого игрока!"
  arg_null: "§c[RedStarAC] §fВы ввели неверные агрументы!"
  reload: "§c[RedStarAC] §fПлагин успешно презагружен!"
  no_player: "§c[RedStarAC] §fИгрок не найден!"
  kick_message: "§cRedStarAC\n\n§fВы кикнуты по подозрению в использовании читов!\n§7(%cheat%)\n\nКлиент: %client%"
  notify_message: "§c[RedStarAC] §fИгрок %cheater% использует читы (%cheat% %count%/%count_max%)"
  notify_message_kick: "§c[RedStarAC] §fИгрок %cheater% был кикнут за использование читов (%cheat% %count%/%count_max%)"